# Лабораторна робота 4
## 2 Варіант

In [80]:
import numpy as np

### $$ A = \begin{pmatrix} 6.26 & 1.10 & 0.98 & 1.25 \\ 1.10 & 4.16 & 1.00 & 0.16 \\ 0.98 & 1.00 & 5.44 & 2.12 \\ 1.25 & 0.16 & 2.12 & 6.00 \end{pmatrix} $$

In [81]:
A = np.array([
    [6.26, 1.10, 0.98, 1.25],
    [1.10, 4.16, 1.00, 0.16],
    [0.98, 1.00, 5.44, 2.12],
    [1.25, 0.16, 2.12, 6.00]
])

## Mетод Данилевського

In [82]:
def danilevsky(A, decimals=4):
    
    A = A.astype(float)
    n = A.shape[0]

    print("Початкова матриця A:\n", A, "\n")

    for k in range(n-1, 0, -1):
        
        print(f"КРОК {n-k}")
        
        M = np.eye(n)
        M_inv = np.eye(n)

        for j in range(n):
            if j == k-1:
                M[k-1, j] = 1 / A[k, k-1]
                M_inv[k-1, j] = A[k, k-1]
            else:
                M[k-1, j] = -A[k, j] / A[k, k-1]
                M_inv[k-1, j] = A[k, j]

        print("M:")
        print(M)
        print("\nM^{-1}:")
        print(M_inv)

        A = M_inv @ A @ M

        print("\nНова матриця A:")
        print(A)
        print("-"*50)

    A[np.abs(A) < 1e-10] = 0
    A_rounded = np.round(A, decimals)

    print("\nМатриця Фробеніуса:")
    print(A_rounded)

    return A_rounded

## Коефіцієнти характеристичного полінома

In [ ]:
def characteristic_polynomial(F):
    
    p = F[0]
    print("\nКоефіцієнти характеристичного полінома:")
    print(p)

    print("\nХарактеристичне рівняння:")
    print(f"x^4 - ({p[0]:.4f})x^3 - ({p[1]:.4f})x^2 - ({p[2]:.4f})x - ({p[3]:.4f}) = 0")

    return lambda x: x**4 - p[0]*x**3 - p[1]*x**2 - p[2]*x - p[3]


## Метод хорд

In [84]:
def chord_method(f, a, b, e):
    c_prev = a  
    iteration = 0

    print(f"\nІнтервал [{a}, {b}]")
    print("i | x_k              | |x_k - x_k-1|")
    print("------------------------------------------------")

    while True:
        c = (a*f(b) - b*f(a)) / (f(b) - f(a))
        iteration += 1
        
        print(f"{iteration:4d} | {c:16.10f} | {abs(c - c_prev):.10f}")
        
        if abs(c - c_prev) < e or abs(f(c)) < e:
            break
        
        if f(a) * f(c) < 0:
            b = c
        else:
            a = c
        
        c_prev = c
    
    return c

## Пошук всіх власних чисел

In [85]:
def intervals(f, a, b, step=0.5):
    intervals = []
    x = a

    while x < b:
        if f(x)*f(x+step) < 0:
            intervals.append((x, x+step))
        x += step

    return intervals

In [86]:
def roots(f):
    
    intervals_list = intervals(f, 0, 10, step=0.5)
    roots = []

    for a, b in intervals_list:
        if f(a)*f(b) < 0:
            root = chord_method(f, a, b, 1e-6)
            roots.append(root)

    return roots

## Результат

In [87]:
F = danilevsky(A)

Початкова матриця A:
 [[6.26 1.1  0.98 1.25]
 [1.1  4.16 1.   0.16]
 [0.98 1.   5.44 2.12]
 [1.25 0.16 2.12 6.  ]] 

КРОК 1
M:
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [-0.58962264 -0.0754717   0.47169811 -2.83018868]
 [ 0.          0.          0.          1.        ]]

M^{-1}:
[[1.   0.   0.   0.  ]
 [0.   1.   0.   0.  ]
 [1.25 0.16 2.12 6.  ]
 [0.   0.   0.   1.  ]]

Нова матриця A:
[[ 5.68216981e+00  1.02603774e+00  4.62264151e-01 -1.52358491e+00]
 [ 5.10377358e-01  4.08452830e+00  4.71698113e-01 -2.67018868e+00]
 [ 2.46197264e+00  3.18567170e+00  1.20933019e+01 -3.04773113e+01]
 [ 9.70293028e-17  1.39301568e-18  1.00000000e+00  0.00000000e+00]]
--------------------------------------------------
КРОК 2
M:
[[ 1.          0.          0.          0.        ]
 [-0.77282686  0.31390554 -3.79615448  9.56699692]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]

M^{-1}:
[[  1

In [88]:
f = characteristic_polynomial(F)


Коефіцієнти характеристичного полінома:
[  21.86   -168.6335  548.5019 -636.9541]

Характеристичне рівняння:
x^4 - (21.8600)x^3 - (-168.6335)x^2 - (548.5019)x - (-636.9541) = 0


In [89]:
r = roots(f)

print("\nВласні числа:")
for i in r:
    print(f"{i:.6f}")


Інтервал [2.5, 3.0]
i | x_k              | |x_k - x_k-1|
------------------------------------------------
   1 |     2.9979656187 | 0.4979656187
   2 |     2.9970531159 | 0.0009125028
   3 |     2.9966445061 | 0.0004086098
   4 |     2.9964616720 | 0.0001828341
   5 |     2.9963798896 | 0.0000817824
   6 |     2.9963433135 | 0.0000365761
   7 |     2.9963269564 | 0.0000163571
   8 |     2.9963196417 | 0.0000073148
   9 |     2.9963163706 | 0.0000032711
  10 |     2.9963149078 | 0.0000014628
  11 |     2.9963142537 | 0.0000006541

Інтервал [4.0, 4.5]
i | x_k              | |x_k - x_k-1|
------------------------------------------------
   1 |     4.2755935998 | 0.2755935998
   2 |     4.2610160126 | 0.0145775871
   3 |     4.2607043489 | 0.0003116637
   4 |     4.2606985094 | 0.0000058395

Інтервал [5.0, 5.5]
i | x_k              | |x_k - x_k-1|
------------------------------------------------
   1 |     5.4189814989 | 0.4189814989
   2 |     5.4509716854 | 0.0319901865
   3 |     5.452