# Лабораторна робота 2
## 2 Варіант

In [19]:
import numpy as np

### Система лінійних рівнянь

\begin{cases}
1.00x_1 + 0.42x_2 + 0.54x_3 + 0.66x_4 = 0.3 \\
0.42x_1 + 1.00x_2 + 0.32x_3 + 0.44x_4 = 0.5 \\
0.54x_1 + 0.32x_2 + 1.00x_3 + 0.22x_4 = 0.7 \\
0.66x_1 + 0.44x_2 + 0.22x_3 + 1.00x_4 = 0.9
\end{cases}


### Оскільки матриця симетрична, тобто (A[i, j] == A[j, i]) для всіх елементів, то використовуємо метод квадратного кореня.

In [20]:
A = np.array([[1, 0.42, 0.54, 0.66],
              [0.42, 1, 0.32, 0.44],
              [0.54, 0.32, 1, 0.22],
              [0.66, 0.44, 0.22, 1]], dtype=float)

b = np.array([0.3, 0.5, 0.7, 0.9], dtype=float)
n = A.shape[0]

### Побудова матриці T :

- Якщо діагональні елементи ($i = j$), то:
$$
t_{ii} = \sqrt{\,a_{ii} - \sum_{k=1}^{i-1} t_{ik}^2\,}
$$

- Якщо недіагональні елементи ($i > j$), то:
$$
t_{ij} = \frac{a_{ij} - \sum_{k=1}^{j-1} t_{ik} t_{jk}}{t_{jj}}
$$

- Якщо $j > i$, то:
$$
t_{ij} = 0
$$

In [21]:
def build_T(A, m):
    
    n = A.shape[0]
    T = np.zeros_like(A, dtype=float)
    
    for i in range(n):
        for j in range(i + 1):

            if i == j:
                sum_ = sum(T[i, k]**2 for k in range(j))
                T[i, j] = np.sqrt(A[i, j] - sum_)
            else:
                sum_ = sum(T[i, k] * T[j, k] for k in range(j))
                T[i, j] = (A[i, j] - sum_) / T[j, j]

            print(f"\n T[{i},{j}]:")
            print(np.round(T, m))

    return T

### Розв'язання Ty = b: $$y_i = \frac{1}{t_{ii}} \left( b_i - \sum_{k=1}^{i-1} t_{ik} y_k \right)$$

In [22]:
def solution_y(T, b, m):
    
    n = len(b)
    y = np.zeros(n, dtype=float)

    print("\nРозв'язання Ty = b:")

    for i in range(n):
        
        sum_ = sum(T[i, k] * y[k] for k in range(i))
        y[i] = (b[i] - sum_) / T[i, i]
        print(f"y[{i}] = {round(y[i], m)}")

    return y

### Розв'язання T'x = y: $$x_i = \frac{1}{t_{ii}} \left( y_i - \sum_{k=i+1}^{n} t_{ki} x_k \right)$$

In [23]:
def solution_x(T, y, m):
    
    n = len(y)
    x = np.zeros(n, dtype=float)

    print("\nРозв'язання T'x = y:")

    for i in reversed(range(n)):
        
        sum_ = sum(T[k, i] * x[k] for k in range(i + 1, n))
        x[i] = (y[i] - sum_) / T[i, i]
        print(f"x[{i}] = {round(x[i], m)}")

    return x

### Обчислення нев’язки: r = |b – Ax|

In [24]:
def vector_neviaska(A, x, b, m):
    
    r = np.abs(b - A @ x)
    print("\nВектор нев'язки r = |b - Ax|:")
    print(np.round(r, m))
    
    return r

### Метод квадратного кореня:

In [25]:
def method_square_root(A, b, m):
    
    T = build_T(A, m)
    y = solution_y(T, b, m)
    x = solution_x(T, y, m)
    r = vector_neviaska(A, x, b, m)

    return x, r

### Результат:

In [26]:
x, r = method_square_root(A, b, m = 6)


 T[0,0]:
[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 T[1,0]:
[[1.   0.   0.   0.  ]
 [0.42 0.   0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   0.  ]]

 T[1,1]:
[[1.       0.       0.       0.      ]
 [0.42     0.907524 0.       0.      ]
 [0.       0.       0.       0.      ]
 [0.       0.       0.       0.      ]]

 T[2,0]:
[[1.       0.       0.       0.      ]
 [0.42     0.907524 0.       0.      ]
 [0.54     0.       0.       0.      ]
 [0.       0.       0.       0.      ]]

 T[2,1]:
[[1.       0.       0.       0.      ]
 [0.42     0.907524 0.       0.      ]
 [0.54     0.102697 0.       0.      ]
 [0.       0.       0.       0.      ]]

 T[2,2]:
[[1.       0.       0.       0.      ]
 [0.42     0.907524 0.       0.      ]
 [0.54     0.102697 0.835376 0.      ]
 [0.       0.       0.       0.      ]]

 T[3,0]:
[[1.       0.       0.       0.      ]
 [0.42     0.907524 0.       0.      ]
 [0.54     0.102697 0.835376 0.      ]
 [0.66     0.       0.       0.